//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.18 at 03:36:27 PM EET 
//


package tr.gov.tubitak.xml.signature;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="HashForSign" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DisplayText" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PhoneNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Operator" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="SigningAlg" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MultiSignature" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "hashForSign",
    "displayText",
    "phoneNumber",
    "operator",
    "signingAlg",
    "multiSignature"
})
@XmlRootElement(name = "SignHashRequest")
public class SignHashRequest {

    @XmlElement(name = "HashForSign", required = true)
    protected String hashForSign;
    @XmlElement(name = "DisplayText", required = true)
    protected String displayText;
    @XmlElement(name = "PhoneNumber", required = true)
    protected String phoneNumber;
    @XmlElement(name = "Operator")
    protected int operator;
    @XmlElement(name = "SigningAlg", required = true)
    protected String signingAlg;
    @XmlElement(name = "MultiSignature")
    protected boolean multiSignature;

    /**
     * Gets the value of the hashForSign property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHashForSign() {
        return hashForSign;
    }

    /**
     * Sets the value of the hashForSign property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHashForSign(String value) {
        this.hashForSign = value;
    }

    /**
     * Gets the value of the displayText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisplayText() {
        return displayText;
    }

    /**
     * Sets the value of the displayText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisplayText(String value) {
        this.displayText = value;
    }

    /**
     * Gets the value of the phoneNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * Sets the value of the phoneNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhoneNumber(String value) {
        this.phoneNumber = value;
    }

    /**
     * Gets the value of the operator property.
     * 
     */
    public int getOperator() {
        return operator;
    }

    /**
     * Sets the value of the operator property.
     * 
     */
    public void setOperator(int value) {
        this.operator = value;
    }

    /**
     * Gets the value of the signingAlg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSigningAlg() {
        return signingAlg;
    }

    /**
     * Sets the value of the signingAlg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSigningAlg(String value) {
        this.signingAlg = value;
    }

    /**
     * Gets the value of the multiSignature property.
     * 
     */
    public boolean isMultiSignature() {
        return multiSignature;
    }

    /**
     * Sets the value of the multiSignature property.
     * 
     */
    public void setMultiSignature(boolean value) {
        this.multiSignature = value;
    }

}
