//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.09 at 04:10:59 PM EET 
//


package tr.gov.tubitak.uekae.esya.api.schemas.signature;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="MultipleSignSupportedReturn" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "multipleSignSupportedReturn"
})
@XmlRootElement(name = "MultipleSignSupportedResponse")
public class MultipleSignSupportedResponse {

    @XmlElement(name = "MultipleSignSupportedReturn")
    protected boolean multipleSignSupportedReturn;

    /**
     * Gets the value of the multipleSignSupportedReturn property.
     * 
     */
    public boolean isMultipleSignSupportedReturn() {
        return multipleSignSupportedReturn;
    }

    /**
     * Sets the value of the multipleSignSupportedReturn property.
     * 
     */
    public void setMultipleSignSupportedReturn(boolean value) {
        this.multipleSignSupportedReturn = value;
    }

}
