//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.24 at 10:32:34 AM EET 
//


package tr.gov.tubitak.uekae.esya.api.schemas.signature;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the tr.gov.tubitak.uekae.esya.api.schemas.signature package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: tr.gov.tubitak.uekae.esya.api.schemas.signature
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SignHashRequest }
     * 
     */
    public SignHashRequest createSignHashRequest() {
        return new SignHashRequest();
    }

    /**
     * Create an instance of {@link SignHashResponse }
     * 
     */
    public SignHashResponse createSignHashResponse() {
        return new SignHashResponse();
    }

    /**
     * Create an instance of {@link CertificateInitialsRequest }
     * 
     */
    public CertificateInitialsRequest createCertificateInitialsRequest() {
        return new CertificateInitialsRequest();
    }

    /**
     * Create an instance of {@link CertificateInitialsResponse }
     * 
     */
    public CertificateInitialsResponse createCertificateInitialsResponse() {
        return new CertificateInitialsResponse();
    }

    /**
     * Create an instance of {@link SigningCertRequest }
     * 
     */
    public SigningCertRequest createSigningCertRequest() {
        return new SigningCertRequest();
    }

    /**
     * Create an instance of {@link Void }
     * 
     */
    public Void createVoid() {
        return new Void();
    }

    /**
     * Create an instance of {@link SigningCertResponse }
     * 
     */
    public SigningCertResponse createSigningCertResponse() {
        return new SigningCertResponse();
    }

    /**
     * Create an instance of {@link SigningCertAttrRequest }
     * 
     */
    public SigningCertAttrRequest createSigningCertAttrRequest() {
        return new SigningCertAttrRequest();
    }

    /**
     * Create an instance of {@link SigningCertAttrResponse }
     * 
     */
    public SigningCertAttrResponse createSigningCertAttrResponse() {
        return new SigningCertAttrResponse();
    }

    /**
     * Create an instance of {@link SigningCertAttrV2Request }
     * 
     */
    public SigningCertAttrV2Request createSigningCertAttrV2Request() {
        return new SigningCertAttrV2Request();
    }

    /**
     * Create an instance of {@link SigningCertAttrV2Response }
     * 
     */
    public SigningCertAttrV2Response createSigningCertAttrV2Response() {
        return new SigningCertAttrV2Response();
    }

    /**
     * Create an instance of {@link SignerIdentifierRequest }
     * 
     */
    public SignerIdentifierRequest createSignerIdentifierRequest() {
        return new SignerIdentifierRequest();
    }

    /**
     * Create an instance of {@link SignerIdentifierResponse }
     * 
     */
    public SignerIdentifierResponse createSignerIdentifierResponse() {
        return new SignerIdentifierResponse();
    }

    /**
     * Create an instance of {@link DigestAlgRequest }
     * 
     */
    public DigestAlgRequest createDigestAlgRequest() {
        return new DigestAlgRequest();
    }

    /**
     * Create an instance of {@link DigestAlgResponse }
     * 
     */
    public DigestAlgResponse createDigestAlgResponse() {
        return new DigestAlgResponse();
    }

}
